POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Susans",
    "name": "Susan Ofcourse",
    "password": "badApple"
}
###
GET http://localhost:3001/api/users
Content-Type: application/json
###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Susans",
    "password": "badApple"
}
